// TODO: Structs, Arrays, Tuples, Loops, Pointers

multiline_comment  = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
singleline_comment = _{ "//" ~ (!"\n" ~ ANY)* }
COMMENT            = _{ multiline_comment | singleline_comment }
WHITESPACE         = _{ " " | "\t" | "\r" | "\n" }


escape       = _{ "\\n" | "\\t" | "\\0" }
char         = @{ "'" ~ (escape | ASCII) ~ "'" }
string_inner = @{ (!"\"" ~ ASCII)* }
string       = ${ "\"" ~ string_inner ~ "\"" }

number  = @{ ("0x" ~ (ASCII_HEX_DIGIT | "_")+) | ("0b" ~ (ASCII_BIN_DIGIT | "_")+) | ("0o" ~ (ASCII_OCT_DIGIT | "_")+) | (ASCII_DIGIT | "_")+ }
true    =  { "true" }
false   =  { "false" }
boolean = @{ true | false }
value = { number | boolean | char | string }

ident_start_chars =  { ASCII_ALPHA | "_" }
ident_chars       =  { ASCII_ALPHANUMERIC | "_" }
ident             = @{ ident_start_chars+ ~ ident_chars* }

struct_type_field = { var_type ~ ident ~ ";" }
struct_type       = { "struct" ~ "{" ~ struct_type_field* ~ "}" }
struct_expr_field = { ident ~ "=" ~ expression ~ ";" }
struct_expr       = { "struct" ~ "{" ~ struct_expr_field* ~ "}" }

array_expr     = { "[" ~  (expression ~ ("," ~ expression)*)? ~ "]" }

array_type_mod = { "[" ~ number ~ "]" }
pointer_type_mod = { "*" }
type_mod = _{ array_type_mod | pointer_type_mod }

char_type    = { "char" }
int_type     = { "int" }
bool_type    = { "bool" }
void_type    = { "void" }
named_type   = { ident }
var_type     = { (char_type | int_type | bool_type | void_type | struct_type | named_type) ~ type_mod* }

typedef = { "typedef" ~ var_type ~ ident ~ ";" }

// Arithmetic operators
add      = { "+" }
subtract = { "-" }
negate   = { "-" }
multiply = { "*" }
divide   = { "/" }
modulo   = { "%" }
power    = { "pow!" }

// Comparison operators
eq = { "==" }
ne = { "!=" }
le = { "<=" }
// Must come before "<" to avoid tokenizing "<=" as "<" + "="
ge = { ">=" }
// Must come before ">" to avoid tokenizing ">=" as ">" + "="
lt = { "<" }
gt = { ">" }

// Logical operators
logical_and = { "&&" }
logical_or  = { "||" }
logical_not = { "!" }

// Bit operators
shr     = { ">>" }
shl     = { "<<" }
bit_and = { "&" }

// Pointer Operators
dereference  = { "*" }
cast         = { "(" ~ var_type ~ ")" }
member       = { "." ~ ident }
member_deref = { "->" ~ ident }
array_idx    = { "[" ~ number ~ "]" }

binary_op  = _{ add | subtract | power | multiply | divide | modulo | shr | shl | eq | ne | le | ge | lt | gt | logical_and | logical_or | bit_and }
prefix_op   = _{ negate | logical_not | dereference | cast }
postfix_op   = _{ member | member_deref | array_idx }
atom       = _{ array_expr | struct_expr | if_statement | sizeof_builtin | function_call | value | ident | ("(" ~ expression ~ ")") }
expression =  { prefix_op* ~ atom ~ postfix_op* ~ (binary_op ~ prefix_op* ~ atom ~ postfix_op*)* }

// A const_var can only take on the value of a literal
const_var      = { "const" ~ var_type ~ ident ~ "=" ~ expression }
local_var      = { var_type ~ ident ~ "=" ~ expression }
pointer_assign = { "*" ~ expression ~ "=" ~ expression }

function_parameters = _{ (expression ~ ("," ~ expression)*)? }
function_call       =  { ident ~ "(" ~ function_parameters ~ ")" }
sizeof_builtin      =  { "sizeof" ~ (("(" ~ (expression) ~ ")") | ("<" ~ (var_type) ~ ">")) }

if_block      =  { "if" ~ "(" ~ expression ~ ")" ~ block }
if_else_block = _{ "else" ~ if_block }
else_block    =  { "else" ~ block }
if_statement  =  { if_block ~ if_else_block* ~ else_block? }

semicolon =  { ";" }
statement = _{ ((const_var | local_var | pointer_assign | expression) ~ semicolon) | function_def | if_statement | typedef }

no_mangle               =  { "no_mangle" }
function_attr           =  { no_mangle }
function_attrs          = _{ ("#" ~ "[" ~ function_attr ~ "]")* }
function_parameters_def = _{ (var_type ~ ident ~ ("," ~ var_type ~ ident)*)? }
function_def            =  { function_attrs ~ var_type ~ ident ~ "(" ~ function_parameters_def ~ ")" ~ block }

block =  { "{" ~ code ~ "}" | statement | expression }
code  = _{ statement* ~ expression? }

program = { SOI ~ code ~ EOI }
